### ISSUE TITLE
Add the ability to vote on the next map in rotation

### ISSUE THREAD

**Issue by NopNotMe** [NopNotMe/RacingXtremev3#2]

**Comment by DriftingCosmos** [comment]
When you #skip the map it does not go for the map you voted for. Only works when the someone finishes the race and the timer goes down naturally.

**Comment by DriftingCosmos** [comment]
maps only show when you reconnect. Maybe a command such as #next can be added to see what upcoming maps their is without reconnecting.

**Comment by NopNotMe** [comment]
Enhancement was added commit 97f74de
